# Generated by Django 4.2.7 on 2023-12-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='cloudinary_url',
            new_name='pdf_file_url',
        ),
    ]
