# Generated by Django 4.2.7 on 2023-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApiApp', '0002_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_documents/'),
        ),
    ]
